version: "0.2"
language:
  - en
  - ru
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - postcondition
  - testcase
  - Testcases
  - Testplan
  - Testplans
ignoreWords: []
import: []
